version: '3.8'

services:
  # Servicio de usuarios
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - user_data:/app/data
      - ./user-service/users.db:/app/users.db
    networks:
      - microservices-network
    restart: unless-stopped

  # Servicio de tareas
  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - USER_SERVICE_URL=http://user-service:3001
    volumes:
      - task_data:/app/data
      - ./task-service/tasks.db:/app/tasks.db
    networks:
      - microservices-network
    depends_on:
      - user-service
    restart: unless-stopped

  # API Gateway (Nginx)
  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-network
    depends_on:
      - user-service
      - task-service
    restart: unless-stopped

# Redes
networks:
  microservices-network:
    driver: bridge
    name: microservices-network

# Volúmenes para persistencia
volumes:
  user_data:
    driver: local
  task_data:
    driver: local